- hosts: localhost
  connection: local
  roles:
    - { role: start-container, host_name: android, image_name: android, container_name: android, dockerfile: Dockerfile }

- hosts: android
  connection: docker
  remote_user: root
  roles:
    - core
    - java
    - android

- hosts: localhost
  connection: local
  roles:
    - { role: stop-container, image_name: android, container_name: android }
